name: Deactivate old Container Apps revisions

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  deactivate-old-revisions:
    uses: TorqIT/pimcore-github-actions-workflows/.github/workflows/job-azure-container-apps-deactivate-revisions.yml@v7
    permissions:
      actions: read
      contents: read
    with:
      ENVIRONMENTS: "['UAT', 'Staging', 'Production']"
    secrets:
      SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
      SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
