name: Ensure Docker images can be built

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ci__${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-images:
    name: Build Docker images
    uses: TorqIT/pimcore-github-actions-workflows/.github/workflows/docker-builds.yml@v7
    permissions:
      contents: read
      actions: read
